import '@/globals.scss'

import type { Metadata } from 'next'

import { Josefin_Sans } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import { twJoin } from 'tailwind-merge'

import { TaskProvider } from '@/contexts/taskContext'

const josefinSans = Josefin_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${josefinSans.className} dark`}>
        <div
          className={twJoin(
            'min-h-dvh w-full',
            'sm:bg-desktop-light md:dark:bg-desktop-dark',
            'bg-mobile-light dark:bg-mobile-dark',
            'bg-contain bg-no-repeat',
            'transition ease-out',
            'bg-background-light dark:bg-background-dark',
          )}>
          <TaskProvider>{children}</TaskProvider>
        </div>
        <Toaster />
      </body>
    </html>
  )
}
