import '@/sass/globals.scss'
import type { Metadata } from 'next'
// import { ReactTreeProvider } from 'react-tree-provider'

// import { AuthProvider } from '@/contexts/authContext'
// import { TaskProvider } from '@/contexts/taskContext'
import { Josefin_Sans } from 'next/font/google'
// ----------------------------------------------------------------------------

const josefinSans = Josefin_Sans({ subsets: ['latin'] })
// const Providers = ReactTreeProvider([[AuthProvider], [TaskProvider]])

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
}

// ============================================================================
type Props = { children: React.ReactNode }
export default function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body className={josefinSans.className + ' dark'}>
        {/* <div
          className={clsx(
            'min-h-dvh w-full',
            'transition ease-out',
            'sm:bg-desktop-light md:dark:bg-desktop-dark',
            'bg-mobile-light bg-contain bg-no-repeat dark:bg-mobile-dark',
            'bg-background-light dark:bg-background-dark',
          )}> */}
        {/* <AuthProvider>
            <TaskProvider>{children}</TaskProvider>
          </AuthProvider> */}
        {/* <Providers>{children}</Providers> */}
        {/* </div> */}
      </body>
    </html>
  )
}
